project:
  type: website
  output-dir: _site

# apply shared metadata (e.g., last-modified) to all pages
metadata-files:
  - _meta.yml

website:
  title: "Vahab Rostampour"
  site-url: "https://vahabr.github.io/"
  favicon: img/favicon.svg   # <-- add this
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Teaching
        href: teaching.qmd
      # - text: Projects
      #   href: projects.qmd
      - text: Research Projects
        href: researchProjects.qmd
      - text: Publications
        href: publications.qmd
    right:
      - icon: github
        href: "https://github.com/vahabr"
        aria-label: "GitHub"
      - icon: linkedin
        href: "https://www.linkedin.com/in/vrostampour"
        aria-label: "LinkedIn"
      - icon: twitter
        href: "https://twitter.com/RostampourVahab"
        aria-label: "X (Twitter)"
      - icon: telegram
        href: "https://t.me/vahabros"
        aria-label: "Telegram"
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=7JPAXgIAAAAJ&hl=en
        aria-label: Google Scholar       
      - icon: envelope
        href: "mailto:rostampour.v@gmail.com"
        aria-label: "Gmail"
      - icon: rss
        href: /posts/
        aria-label: "Blog"

  page-footer:
    center: >-
      <span class="footer-line">
        © <span class="current-year"></span> Vahab Rostampour . Outreach .
        <span class="footer-icons">
          <a href="https://github.com/vahabr" aria-label="GitHub"><i class="bi bi-github"></i></a>
          <a href="https://www.linkedin.com/in/vrostampour" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
          <a href="https://twitter.com/RostampourVahab" aria-label="Twitter/X"><i class="bi bi-twitter"></i></a>
          <a href="https://t.me/vahabros" aria-label="Telegram"><i class="bi bi-telegram"></i></a>
          <a href="https://scholar.google.com/citations?user=7JPAXgIAAAAJ&hl=en" aria-label="Google Scholar"><i class="bi bi-mortarboard"></i></a>
          <a href="mailto:rostampour.v@gmail.com" aria-label="Gmail"><i class="bi bi-envelope"></i></a>
          <a href="/posts/" aria-label="Blog"><i class="bi bi-rss"></i></a>
        </span>
      </span>

      <script>
        document.querySelectorAll('.current-year').forEach(e => e.textContent = new Date().getFullYear());
      </script>

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: right
    code-copy: true
    css: styles.scss
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
      - _includes/head.html
    code-tools: false
    thebe: true

resources:
  - img/

