project:
  type: website
  output-dir: _site

website:
  title: "Vahab Rostampour"
  site-url: https://vahabr.github.io/
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Projects
        href: projects.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/vahabr

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-copy: true
    css: styles.scss

resources:
  - img/
